# This file has been modified from generated version
# see https://github.com/hvr/multi-ghc-travis
language: c
sudo: false

# Bryan threatens to turn off Travis-CI if he gets any email :-)
notifications:
  email: false

cache:
  directories:
    - $HOME/.stack
    - $HOME/.cabsnap
    - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

matrix:
  include:
    - env: BUILD=hlint CABALVER=2.0 GHCVER=8.2.1
      compiler: ": #GHC 8.2.1"
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.1], sources: [hvr-ghc]}}
    - env: BUILD=stack CABALVER=2.0 GHCVER=8.2.1 STACK_YAML=stack-bench.yaml
      compiler: ": #GHC 8.2.1"
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.1], sources: [hvr-ghc]}}
    - env: BUILD=stack CABALVER=2.0 GHCVER=8.2.1 STACK_YAML=stack-ffi-unescape.yaml
      compiler: ": #GHC 8.2.1"
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=2.0 GHCVER=8.0.2
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.18 GHCVER=7.4.2
      compiler: ": #GHC 7.4.2"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.4.2], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.18 GHCVER=7.6.3
      compiler: ": #GHC 7.6.3"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.6.3], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.18 GHCVER=7.8.4
      compiler: ": #GHC 7.8.4"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.3
      compiler: ": #GHC 7.10.3"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}

before_install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 # Download and unpack the stack executable
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
 - travis/install.sh

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - travis/script.sh

# EOF
